=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Corrigo::LinkUserAndCustomerGroupAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Corrigo::LinkUserAndCustomerGroupAllOf do
  let(:instance) { Corrigo::LinkUserAndCustomerGroupAllOf.new }

  describe 'test an instance of LinkUserAndCustomerGroupAllOf' do
    it 'should create an instance of LinkUserAndCustomerGroupAllOf' do
      expect(instance).to be_instance_of(Corrigo::LinkUserAndCustomerGroupAllOf)
    end
  end
  describe 'test attribute "user_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "customer_group_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
