=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Corrigo::MatchAssetsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Corrigo::MatchAssetsResponse do
  let(:instance) { Corrigo::MatchAssetsResponse.new }

  describe 'test an instance of MatchAssetsResponse' do
    it 'should create an instance of MatchAssetsResponse' do
      expect(instance).to be_instance_of(Corrigo::MatchAssetsResponse)
    end
  end
  describe 'test attribute "error_info"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "locations"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
