=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Corrigo::OrderType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Corrigo::OrderType do
  let(:instance) { Corrigo::OrderType.new }

  describe 'test an instance of OrderType' do
    it 'should create an instance of OrderType' do
      expect(instance).to be_instance_of(Corrigo::OrderType)
    end
  end
end
