=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Corrigo::WarrantyStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Corrigo::WarrantyStatus do
  let(:instance) { Corrigo::WarrantyStatus.new }

  describe 'test an instance of WarrantyStatus' do
    it 'should create an instance of WarrantyStatus' do
      expect(instance).to be_instance_of(Corrigo::WarrantyStatus)
    end
  end
end
