=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Corrigo::WorkZoneDeleteCommandAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Corrigo::WorkZoneDeleteCommandAllOf do
  let(:instance) { Corrigo::WorkZoneDeleteCommandAllOf.new }

  describe 'test an instance of WorkZoneDeleteCommandAllOf' do
    it 'should create an instance of WorkZoneDeleteCommandAllOf' do
      expect(instance).to be_instance_of(Corrigo::WorkZoneDeleteCommandAllOf)
    end
  end
  describe 'test attribute "work_zone_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
