=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class BillingRule
    UNKNOWN = "Unknown".freeze
    VENDOR_AND_SERVICE_FEE = "VendorAndServiceFee".freeze
    CONTRACT = "Contract".freeze
    NOT_BILLED = "NotBilled".freeze
    SERVICE_FEE = "ServiceFee".freeze
    ALL = "All".freeze
    COSTS_AND_FEES = "CostsAndFees".freeze
    APPROVED_ESTIMATE = "ApprovedEstimate".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, VENDOR_AND_SERVICE_FEE, CONTRACT, NOT_BILLED, SERVICE_FEE, ALL, COSTS_AND_FEES, APPROVED_ESTIMATE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BillingRule.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BillingRule"
    end
  end
end
