=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class CfType
    UNKNOWN = "Unknown".freeze
    STRING = "String".freeze
    INTEGER = "Integer".freeze
    DECIMAL = "Decimal".freeze
    MONEY = "Money".freeze
    PHONE = "Phone".freeze
    DATE = "Date".freeze
    TIME = "Time".freeze
    BOOLEAN = "Boolean".freeze
    URL = "Url".freeze
    TEXT = "Text".freeze
    STRING_AUTOCOMPLETE = "StringAutocomplete".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, STRING, INTEGER, DECIMAL, MONEY, PHONE, DATE, TIME, BOOLEAN, URL, TEXT, STRING_AUTOCOMPLETE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CfType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CfType"
    end
  end
end
