=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class CiInvoiceState
    DRAFT = "Draft".freeze
    POSTED = "Posted".freeze
    CREDIT = "Credit".freeze
    CREDIT_USED = "CreditUsed".freeze
    PAID = "Paid".freeze
    PAID_IN_FULL = "PaidInFull".freeze
    APPROVED = "Approved".freeze

    def self.all_vars
      @all_vars ||= [DRAFT, POSTED, CREDIT, CREDIT_USED, PAID, PAID_IN_FULL, APPROVED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CiInvoiceState.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CiInvoiceState"
    end
  end
end
