=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class CurrencyType
    UNKNOWN = "Unknown".freeze
    VUV = "VUV".freeze
    FJD = "FJD".freeze
    PGK = "PGK".freeze
    TOP = "TOP".freeze
    CFP = "CFP".freeze
    SBD = "SBD".freeze
    WST = "WST".freeze
    MUR = "MUR".freeze
    BMD = "BMD".freeze
    SAR = "SAR".freeze
    BGN = "BGN".freeze
    TWD = "TWD".freeze
    CZK = "CZK".freeze
    DKK = "DKK".freeze
    EUR = "EUR".freeze
    USD = "USD".freeze
    ILS = "ILS".freeze
    HUF = "HUF".freeze
    JPY = "JPY".freeze
    KRW = "KRW".freeze
    PLN = "PLN".freeze
    BRL = "BRL".freeze
    RON = "RON".freeze
    RUB = "RUB".freeze
    HRK = "HRK".freeze
    SEK = "SEK".freeze
    THB = "THB".freeze
    TRY = "TRY".freeze
    PKR = "PKR".freeze
    IDR = "IDR".freeze
    VND = "VND".freeze
    AMD = "AMD".freeze
    ZAR = "ZAR".freeze
    INR = "INR".freeze
    MYR = "MYR".freeze
    KZT = "KZT".freeze
    KES = "KES".freeze
    KHR = "KHR".freeze
    MMK = "MMK".freeze
    LKR = "LKR".freeze
    PHP = "PHP".freeze
    NGN = "NGN".freeze
    CNY = "CNY".freeze
    CHF = "CHF".freeze
    GBP = "GBP".freeze
    MXN = "MXN".freeze
    BND = "BND".freeze
    NOK = "NOK".freeze
    BDT = "BDT".freeze
    EGP = "EGP".freeze
    HKD = "HKD".freeze
    AUD = "AUD".freeze
    SGD = "SGD".freeze
    CAD = "CAD".freeze
    DZD = "DZD".freeze
    MOP = "MOP".freeze
    NZD = "NZD".freeze
    CRC = "CRC".freeze
    MAD = "MAD".freeze
    TND = "TND".freeze
    OMR = "OMR".freeze
    VES = "VES".freeze
    COP = "COP".freeze
    PEN = "PEN".freeze
    JOD = "JOD".freeze
    ARS = "ARS".freeze
    LBP = "LBP".freeze
    KWD = "KWD".freeze
    CLP = "CLP".freeze
    AED = "AED".freeze
    UYU = "UYU".freeze
    BHD = "BHD".freeze
    QAR = "QAR".freeze
    RSD = "RSD".freeze
    AZN = "AZN".freeze
    UZS = "UZS".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, VUV, FJD, PGK, TOP, CFP, SBD, WST, MUR, BMD, SAR, BGN, TWD, CZK, DKK, EUR, USD, ILS, HUF, JPY, KRW, PLN, BRL, RON, RUB, HRK, SEK, THB, TRY, PKR, IDR, VND, AMD, ZAR, INR, MYR, KZT, KES, KHR, MMK, LKR, PHP, NGN, CNY, CHF, GBP, MXN, BND, NOK, BDT, EGP, HKD, AUD, SGD, CAD, DZD, MOP, NZD, CRC, MAD, TND, OMR, VES, COP, PEN, JOD, ARS, LBP, KWD, CLP, AED, UYU, BHD, QAR, RSD, AZN, UZS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CurrencyType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CurrencyType"
    end
  end
end
