=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class IsmStatus
    NOT_APPLICABLE = "NotApplicable".freeze
    NOT_REQUIRED = "NotRequired".freeze
    PASSED = "Passed".freeze
    PASSED_MANUAL = "PassedManual".freeze
    WAITING = "Waiting".freeze
    STARTED = "Started".freeze

    def self.all_vars
      @all_vars ||= [NOT_APPLICABLE, NOT_REQUIRED, PASSED, PASSED_MANUAL, WAITING, STARTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if IsmStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #IsmStatus"
    end
  end
end
