=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class JurisdictionType
    COUNTRY = "Country".freeze
    COMPOSITE = "Composite".freeze
    STATE = "State".freeze
    COUNTY = "County".freeze
    CITY = "City".freeze
    SPECIAL = "Special".freeze

    def self.all_vars
      @all_vars ||= [COUNTRY, COMPOSITE, STATE, COUNTY, CITY, SPECIAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if JurisdictionType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #JurisdictionType"
    end
  end
end
