=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class MhOrderStatus
    UNKNOWN = "Unknown".freeze
    PENDING = "Pending".freeze
    ON_ORDER = "OnOrder".freeze
    SHIPPED = "Shipped".freeze
    RECEIVED = "Received".freeze
    PARTIAL = "Partial".freeze
    CANCELLED = "Cancelled".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, PENDING, ON_ORDER, SHIPPED, RECEIVED, PARTIAL, CANCELLED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MhOrderStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MhOrderStatus"
    end
  end
end
