=begin
#Corrigo Api Integration

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Corrigo
  class NewUnitSpecifier
    attr_accessor :building_name

    attr_accessor :building_floor_plan

    attr_accessor :floor_name

    attr_accessor :floor_floor_plan

    attr_accessor :unit_name

    attr_accessor :unit_floor_plan

    attr_accessor :street_address

    attr_accessor :unit_info

    attr_accessor :space_name

    attr_accessor :space_floor_plan

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'building_name' => :'BuildingName',
        :'building_floor_plan' => :'BuildingFloorPlan',
        :'floor_name' => :'FloorName',
        :'floor_floor_plan' => :'FloorFloorPlan',
        :'unit_name' => :'UnitName',
        :'unit_floor_plan' => :'UnitFloorPlan',
        :'street_address' => :'StreetAddress',
        :'unit_info' => :'UnitInfo',
        :'space_name' => :'SpaceName',
        :'space_floor_plan' => :'SpaceFloorPlan'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'building_name' => :'String',
        :'building_floor_plan' => :'String',
        :'floor_name' => :'String',
        :'floor_floor_plan' => :'String',
        :'unit_name' => :'String',
        :'unit_floor_plan' => :'String',
        :'street_address' => :'Address2',
        :'unit_info' => :'AssetInfo',
        :'space_name' => :'String',
        :'space_floor_plan' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Corrigo::NewUnitSpecifier` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Corrigo::NewUnitSpecifier`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'building_name')
        self.building_name = attributes[:'building_name']
      end

      if attributes.key?(:'building_floor_plan')
        self.building_floor_plan = attributes[:'building_floor_plan']
      end

      if attributes.key?(:'floor_name')
        self.floor_name = attributes[:'floor_name']
      end

      if attributes.key?(:'floor_floor_plan')
        self.floor_floor_plan = attributes[:'floor_floor_plan']
      end

      if attributes.key?(:'unit_name')
        self.unit_name = attributes[:'unit_name']
      end

      if attributes.key?(:'unit_floor_plan')
        self.unit_floor_plan = attributes[:'unit_floor_plan']
      end

      if attributes.key?(:'street_address')
        self.street_address = attributes[:'street_address']
      end

      if attributes.key?(:'unit_info')
        self.unit_info = attributes[:'unit_info']
      end

      if attributes.key?(:'space_name')
        self.space_name = attributes[:'space_name']
      end

      if attributes.key?(:'space_floor_plan')
        self.space_floor_plan = attributes[:'space_floor_plan']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          building_name == o.building_name &&
          building_floor_plan == o.building_floor_plan &&
          floor_name == o.floor_name &&
          floor_floor_plan == o.floor_floor_plan &&
          unit_name == o.unit_name &&
          unit_floor_plan == o.unit_floor_plan &&
          street_address == o.street_address &&
          unit_info == o.unit_info &&
          space_name == o.space_name &&
          space_floor_plan == o.space_floor_plan
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [building_name, building_floor_plan, floor_name, floor_floor_plan, unit_name, unit_floor_plan, street_address, unit_info, space_name, space_floor_plan].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Corrigo.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
